ignoreGeneratedHeader = false
# severity = "warning"
severity = "info"
confidence = 0.8
errorCode = 0
warningCode = 0
# enableAllRules = true

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.empty-lines]
# [rule.exported]
	# Disabled = true 
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration] 
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.struct-tag]
[rule.time-equal]
[rule.unhandled-error]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
